version: '2.28.1'

services:
  smart-brain-app:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: adrian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_HOST: postgres

    links:
      - postgres
    volumes:
      - ./:/app/
      - /app/node_modules

  postgres: 
    image: postgres
    environment:
      POSTGRES_USER: adrian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"